# Generated by Django 5.0.4 on 2024-06-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('MaDanhMuc', models.IntegerField(primary_key=True, serialize=False)),
                ('TenDanhMuc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSanPham', models.IntegerField(primary_key=True, serialize=False)),
                ('TenSanPham', models.CharField(max_length=255)),
                ('MoTa', models.TextField()),
                ('Gia', models.FloatField()),
                ('HinhAnhDaiDien', models.CharField(max_length=100)),
                ('NhanHieu', models.CharField(max_length=100)),
                ('MaDanhMuc_id', models.IntegerField()),
            ],
        ),
    ]
