# Generated by Django 5.0.4 on 2024-06-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_chitietsanpham_donhang_khachhang_chitietdonhang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('tendangnhap', models.CharField(max_length=100)),
                ('matkhau', models.CharField(max_length=100)),
            ],
        ),
    ]
